FROM ubuntu:22.04

RUN apt update && apt install -y git 
RUN mkdir -p /robot_ws/src
RUN git clone https://github.com/samlovelace/vision.git /robot_ws/src/vision

ENTRYPOINT [ "/robot_ws/src/vision/setup.sh" ]




